[project]
name = "fezf2-multiomics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anndata>=0.12.11",
    "cellrank>=2.0.7",
    "decoupler>=2.1.6",
    "harmony>=1.2.4126",
    "harmonypy>=2.0.0",
    "jupyterlab>=4.5.7",
    "matplotlib>=3.10.9",
    "muon>=0.1.7",
    "scanpy>=1.11.5",
    "scrublet>=0.2.3",
    "scvi-tools>=1.4.2",
    "seaborn>=0.13.2",
]
